version: '3'
services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - 4202:4202
    command: yarn start:dev
    volumes:
      - .:/usr/src/app

  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: dev
